### ISSUE TITLE
Update icons URL and improvements

### ISSUE THREAD

**Issue by orifer** [telmobarros/tw-farm-assistant#3]
Hello, I'm loving your farm assistant. 
However, there is an issue with the icons since the url has expired and need to be fixed.

Also, it would be nice to send troops to all the villages from a single button.

Please tell me if you can fix this soon. If not, i could do it but i have no idea about the chrome extensions.

Thanks!

**Comment by telmobarros** [comment]
Hello, glad to see you liked!

Just saw your PR #4  #`` and will accept right away.

Regarding sending troops to all the villages I will add this to upcoming features and close this issue.

Thank you 👍 😄
